compress_assets: on
javascript_compressor: yui
embed_assets: datauri
package_assets: on

javascripts:
  common:
    - public/javascripts/jquery-1.5.1.js
    - public/javascripts/application.js
    - public/javascripts/rails.js
    - public/javascripts/mobiscroll-1.5.js
    - public/javascripts/autoresize.jquery.js
    - public/javascripts/site_specific/main_map.js
    - public/javascripts/ss_MarkerManager.js
    - public/javascripts/ss_keywords.js
    - public/javascripts/ss_pageless.js
    - public/javascripts/jquery.jscrollpane.js
    - public/javascripts/jquery.mousewheel.js
    - public/javascripts/mwheelIntent.js
    - public/javascripts/autoresize.jquery.js
stylesheets:
  common:
    - public/stylesheets/all.css
    - public/stylesheets/mobiscroll-1.5.css
    - public/stylesheets/jquery.jscrollpane
    - public/stylesheets/fullcalendar
  ie:
    - public/stylesheets/ie.css
  ie7: 
    - public/stylesheets/ie7.css
