embed_assets: on

javascripts:
  common:
    - public/javascripts/jquery-1.5.1.js
    - public/jquery-ui-1.8.11.custom/js/jquery-ui-1.8.11.custom.min.js
    - public/javascripts/rails.js
    - public/javascripts/ss.js
    - public/javascripts/autoresize.jquery.min.js
    - public/javascripts/jquery.ui.autocomplete.html.js
    - public/javascripts/infobubble.js

stylesheets:
  common:
    - public/stylesheets/all.css
    - public/jquery-ui-1.8.11.custom/css/smoothness/jquery-ui-1.8.11.custom.css