compress_assets: on
javascript_compressor: yui
embed_assets: datauri
package_assets: on

javascripts:
  init:
#    - public/javascripts/jquery-1.5.1.js
    - public/jquery-ui-1.8.11.custom/js/jquery-ui-1.8.11.custom.min.js
#    - public/javascripts/jquery_ujs.js
    

  common:
    - public/javascripts/ss_markerManager.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/jquerym_custom.js
    - public/javascripts/jquery.ui.map.js
    - public/javascripts/jquery.ui.map.extensions.js
    - public/javascripts/jquery.ui.map.services.js
    - public/javascripts/ss_pageless.js
    - public/javascripts/mobiscroll-1.5.js
    - public/javascripts/infobubble.js
    - public/javascripts/ss.js
    - public/javascripts/date.js
    - public/javascripts/iscroll-lite.js
   
  
stylesheets:
  common:
    - public/stylesheets/mobiscroll-1.5.css
    - public/stylesheets/mobile.css
  
#- public/javascripts/ss.js
#- public/stylesheets/all.css