twitter_app_consumer_key: 'Your apps consumer key goes here'
twitter_app_consumer_secret: 'Your apps consumer secret goes here'
facebook_app_id: 'Your facebok APP ID goes here'
facebook_app_secret: 'Your facebook APP SECRET goes here'