#! /bin/bash

echo ">>>Starting Resque Server"
/usr/bin/redis-2.2.7/src/redis-server&

cd /Users/joshuaborts/Work/personal_work/SocialStreet_reborn

echo ">>>Starting Resque Worker"
QUEUE=* bundle exec rake environment resque:work&

echo ">>>Starting Resque Web Server"
bundle exec resque-web ./config/resque_config.rb&

echo ">>>Starting Rails Server"
rails server&
