#! /bin/bash

echo ">>>Starting Resque Server"
/Users/azhar/Downloads/Applications/redis-2.2.12/src/redis-server&

cd /Users/azhar/SocialStreet

echo ">>>Starting Resque Worker"
QUEUE=* bundle exec rake environment resque:work&

echo ">>>Starting Resque Web Server"
bundle exec resque-web ~/SocialStreet/config/resque_config.rb&

echo ">>>Starting Rails Server"
rails server&
